<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>CitadelX.Backend.Abstractions</AssemblyName>
    <RootNamespace>CitadelX.Backend</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CitadelX.Modules.Abstractions\CitadelX.Modules.Abstractions.csproj" />
  </ItemGroup>
</Project>
